/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public enum ECIES_ITEMS {
  ECIES_PUBKEY,
  ECIES_PRIKEY,
  ECIES_ENCSYNCKEY,
  ECIES_ENCHASH,
  ECIES_ENCTEXT,
  ECIES_ENCALLOUT
}

}
