/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public enum JCCMD {
  JCCMD_GEN_DYNACODE,
  JCCMD_CCB_DYPASS1,
  JCCMD_CCB_LOCK_VERCODE,
  JCCMD_CCB_DYPASS2,
  JCCMD_RESET_KEY
}

}
