/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public enum JCCMD {
  JCCMD_START,
  JCCMD_INIT_CLOSECODE,
  JCCMD_CCB_DYPASS1,
  JCCMD_CCB_LOCK_VERCODE,
  JCCMD_CCB_DYPASS2,
  JCCMD_CCB_CLOSECODE,
  JCCMD_RESET_NFCKEY,
  JCCMD_RESET_LOCKTIME,
  JCCMD_RESET_LOCKSYSTEM,
  JCCMD_GET_LOCKLOG,
  JCCMD_END
}

}
