/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public enum JCERROR {
  EJC_SUSSESS,
  EJC_FAIL,
  EJC_INPUT_NULL,
  EJC_DATETIME_INVALID,
  EJC_VALIDRANGE_INVALID,
  EJC_CLOSECODE_INVALID,
  EJC_CMDTYPE_INVALID
}

}
