/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public class JCINPUT : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal JCINPUT(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(JCINPUT obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~JCINPUT() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          jclmsCCB2014PINVOKE.delete_JCINPUT(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AtmNo {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_AtmNo_set(swigCPtr, value);
    } 
    get {
      string ret = jclmsCCB2014PINVOKE.JCINPUT_AtmNo_get(swigCPtr);
      return ret;
    } 
  }

  public string LockNo {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_LockNo_set(swigCPtr, value);
    } 
    get {
      string ret = jclmsCCB2014PINVOKE.JCINPUT_LockNo_get(swigCPtr);
      return ret;
    } 
  }

  public string PSK {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_PSK_set(swigCPtr, value);
    } 
    get {
      string ret = jclmsCCB2014PINVOKE.JCINPUT_PSK_get(swigCPtr);
      return ret;
    } 
  }

  public int CodeGenDateTime {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_CodeGenDateTime_set(swigCPtr, value);
    } 
    get {
      int ret = jclmsCCB2014PINVOKE.JCINPUT_CodeGenDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public int Validity {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_Validity_set(swigCPtr, value);
    } 
    get {
      int ret = jclmsCCB2014PINVOKE.JCINPUT_Validity_get(swigCPtr);
      return ret;
    } 
  }

  public int CloseCode {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_CloseCode_set(swigCPtr, value);
    } 
    get {
      int ret = jclmsCCB2014PINVOKE.JCINPUT_CloseCode_get(swigCPtr);
      return ret;
    } 
  }

  public JCCMD CmdType {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_CmdType_set(swigCPtr, (int)value);
    } 
    get {
      JCCMD ret = (JCCMD)jclmsCCB2014PINVOKE.JCINPUT_CmdType_get(swigCPtr);
      return ret;
    } 
  }

  public int SearchTimeStart {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_SearchTimeStart_set(swigCPtr, value);
    } 
    get {
      int ret = jclmsCCB2014PINVOKE.JCINPUT_SearchTimeStart_get(swigCPtr);
      return ret;
    } 
  }

  public int SearchTimeStep {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_SearchTimeStep_set(swigCPtr, value);
    } 
    get {
      int ret = jclmsCCB2014PINVOKE.JCINPUT_SearchTimeStep_get(swigCPtr);
      return ret;
    } 
  }

  public int SearchTimeLength {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_SearchTimeLength_set(swigCPtr, value);
    } 
    get {
      int ret = jclmsCCB2014PINVOKE.JCINPUT_SearchTimeLength_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_int ValidityArray {
    set {
      jclmsCCB2014PINVOKE.JCINPUT_ValidityArray_set(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = jclmsCCB2014PINVOKE.JCINPUT_ValidityArray_get(swigCPtr);
      SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
      return ret;
    } 
  }

  public JCINPUT() : this(jclmsCCB2014PINVOKE.new_JCINPUT(), true) {
  }

}

}
