/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public class JCLMSREQ : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal JCLMSREQ(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(JCLMSREQ obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~JCLMSREQ() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          jclmsCCB2014PINVOKE.delete_JCLMSREQ(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public JCLMSOP Type {
    set {
      jclmsCCB2014PINVOKE.JCLMSREQ_Type_set(swigCPtr, (int)value);
    } 
    get {
      JCLMSOP ret = (JCLMSOP)jclmsCCB2014PINVOKE.JCLMSREQ_Type_get(swigCPtr);
      return ret;
    } 
  }

  public int dstCode {
    set {
      jclmsCCB2014PINVOKE.JCLMSREQ_dstCode_set(swigCPtr, value);
    } 
    get {
      int ret = jclmsCCB2014PINVOKE.JCLMSREQ_dstCode_get(swigCPtr);
      return ret;
    } 
  }

  public JCINPUT inputData {
    set {
      jclmsCCB2014PINVOKE.JCLMSREQ_inputData_set(swigCPtr, JCINPUT.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = jclmsCCB2014PINVOKE.JCLMSREQ_inputData_get(swigCPtr);
      JCINPUT ret = (cPtr == global::System.IntPtr.Zero) ? null : new JCINPUT(cPtr, false);
      return ret;
    } 
  }

  public JCLMSREQ() : this(jclmsCCB2014PINVOKE.new_JCLMSREQ(), true) {
  }

}

}
