/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

using System;
using System.Runtime.InteropServices;

public class zwHexTool : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal zwHexTool(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(zwHexTool obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~zwHexTool() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          jclmsCCB2014PINVOKE.delete_zwHexTool(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public zwHexTool(string HexInput) : this(jclmsCCB2014PINVOKE.new_zwHexTool__SWIG_0(HexInput), true) {
  }

  public zwHexTool(SWIGTYPE_p_void msg, int msgLen) : this(jclmsCCB2014PINVOKE.new_zwHexTool__SWIG_1(SWIGTYPE_p_void.getCPtr(msg), msgLen), true) {
  }

  public string getBin() {
    string ret = jclmsCCB2014PINVOKE.zwHexTool_getBin(swigCPtr);
    return ret;
  }

  public int getBinLen() {
    int ret = jclmsCCB2014PINVOKE.zwHexTool_getBinLen(swigCPtr);
    return ret;
  }

  public int getPadedLen() {
    int ret = jclmsCCB2014PINVOKE.zwHexTool_getPadedLen(swigCPtr);
    return ret;
  }

  public int getXXTEABlockNum() {
    int ret = jclmsCCB2014PINVOKE.zwHexTool_getXXTEABlockNum(swigCPtr);
    return ret;
  }

  public void PrintBin() {
    jclmsCCB2014PINVOKE.zwHexTool_PrintBin(swigCPtr);
  }

  public string getCArrayStr() {
    string ret = jclmsCCB2014PINVOKE.zwHexTool_getCArrayStr(swigCPtr);
    return ret;
  }

}

}
