/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public enum ECIES_ERROR {
  ECIES_SUCCESS,
  ECIES_FAIL,
  ECIES_OUTPUT_BUFFER_TOO_SHORT,
  ECIES_PRIKEY_TOO_SHORT,
  ECIES_PUBKEY_TOO_SHORT,
  ECIES_HASH_TOO_SHORT,
  ECIES_CRYPT_TOO_SHORT,
  ECIES_ENCEDSYNCKEY_TOO_SHORT,
  ECIES_PLAIN_TOO_SHORT,
  ECIES_PUBKEY_GEN_FAIL,
  ECIES_INPUT_TOO_SHORT,
  ECIES_INPUT_NULL,
  ECIES_INIT_FLAG
}

}
