/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public enum JCITYPE {
  JCI_START,
  JCI_ATMNO,
  JCI_LOCKNO,
  JCI_PSK,
  JCI_DATETIME,
  JCI_VALIDITY,
  JCI_CLOSECODE,
  JCI_CMDTYPE,
  JCI_TIMESTEP,
  JCI_SEARCH_TIME_LENGTH,
  JCI_SEARCH_TIME_START,
  JCI_END
}

}
