/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public enum JCLMSOP {
  JCLMS_CCB_INVALID,
  JCLMS_CCB_CODEGEN,
  JCLMS_CCB_CODEVERIFY
}

}
