/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public class JCRESULT : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal JCRESULT(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(JCRESULT obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~JCRESULT() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          jclmsCCB2014PINVOKE.delete_JCRESULT(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int dynaCode {
    set {
      jclmsCCB2014PINVOKE.JCRESULT_dynaCode_set(swigCPtr, value);
    } 
    get {
      int ret = jclmsCCB2014PINVOKE.JCRESULT_dynaCode_get(swigCPtr);
      return ret;
    } 
  }

  public JCMATCH verCodeMatch {
    set {
      jclmsCCB2014PINVOKE.JCRESULT_verCodeMatch_set(swigCPtr, JCMATCH.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = jclmsCCB2014PINVOKE.JCRESULT_verCodeMatch_get(swigCPtr);
      JCMATCH ret = (cPtr == global::System.IntPtr.Zero) ? null : new JCMATCH(cPtr, false);
      return ret;
    } 
  }

  public JCRESULT() : this(jclmsCCB2014PINVOKE.new_JCRESULT(), true) {
  }

}

}
