/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public class zwHexTool : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal zwHexTool(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(zwHexTool obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~zwHexTool() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          jclmsCCB2014PINVOKE.delete_zwHexTool(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public zwHexTool(string HexInput) : this(jclmsCCB2014PINVOKE.new_zwHexTool__SWIG_0(HexInput), true) {
  }

  public zwHexTool(SWIGTYPE_p_void msg, int msgLen) : this(jclmsCCB2014PINVOKE.new_zwHexTool__SWIG_1(SWIGTYPE_p_void.getCPtr(msg), msgLen), true) {
  }

  public string getBin() {
    string ret = jclmsCCB2014PINVOKE.zwHexTool_getBin(swigCPtr);
    return ret;
  }

  public int getBinLen() {
    int ret = jclmsCCB2014PINVOKE.zwHexTool_getBinLen(swigCPtr);
    return ret;
  }

  public int getPadedLen() {
    int ret = jclmsCCB2014PINVOKE.zwHexTool_getPadedLen(swigCPtr);
    return ret;
  }

  public int getXXTEABlockNum() {
    int ret = jclmsCCB2014PINVOKE.zwHexTool_getXXTEABlockNum(swigCPtr);
    return ret;
  }

  public void PrintBin() {
    jclmsCCB2014PINVOKE.zwHexTool_PrintBin(swigCPtr);
  }

  public string getCArrayStr() {
    string ret = jclmsCCB2014PINVOKE.zwHexTool_getCArrayStr(swigCPtr);
    return ret;
  }

}

}
